[project]
name = "deep_neuronmorpho"
version = "0.0.1"
requires-python = ">=3.11"
description = "Deep learning based approaches for neuron morphology embeddings."
authors = [{ name = "Kyle Puhger", email = "krpuhger@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
  "numpy",
  "torch==2.3.0",
  "pytorch-lightning>=2.4.0",
  "dgl==2.2.1; sys_platform == 'darwin'",
  "dgl==2.2.1+cu121; sys_platform == 'linux'",
  "scikit-learn",
  "tensorboard",
  "scipy==1.12",
  "pandas",
  "seaborn",
  "matplotlib",
  "xgboost",
  "umap-learn",
  "morphopy",
  "pyyaml",
  "pyarrow",
  "pydantic",
  "typer",
]

[project.optional-dependencies]
dev = [
  "pip",
  "ruff",
  "mypy",
  "pre-commit",
  "notebook",
  "pandas-stubs",
  "pytest",
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
]

[project.urls]
repository = "https://github.com/kpeez/deep-neuronmorpho"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
index-strategy = "unsafe-best-match"
find-links = [
  "https://data.dgl.ai/wheels/torch-2.3/cu121/repo.html",
  "https://data.dgl.ai/wheels/repo.html",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--log-cli-level=INFO -sv --durations=0"

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [".venv", "external"]

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  "W",
  # pyflakes
  "F",
  # pylint
  "PL",
  # isort
  "I",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # flake8-comprehensions
  "C4",
  # ruff
  "RUF",
]
fixable = ["ALL"]
ignore = [
  # too many branches
  "PLR0912",
  # too many arguments
  "PLR0913",
  # too many local variables
  "PLR0914",
  # too many statements
  "PLR0915",
  # too many positional arguments
  "PLR0917",
  # magic number
  "PLR2004",
  # line too long
  "E501",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "D104"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
files = ["deep_neuronmorpho"]
plugins = "numpy.typing.mypy_plugin"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
exclude = [".venv", "tests", "external"]

[[tool.mypy.overrides]]
module = [
  "deep_neuronmorpho.*",
  "deep_neuronmorpho.*.*",
  "morphopy.*",
  "networkx",
  "scipy.*",
  "sklearn.*",
  "dgl.*",
  "seaborn",
  "umap",
]
ignore_missing_imports = true
warn_return_any = false
disallow_any_unimported = false
disable_error_code = "attr-defined"
