[tool.poetry]
name = "deep_neuronmorpho"
version = "0.0.1"
description = "Deep learning based approaches for neuron morphology embeddings."
authors = ["Kyle Puhger <krpuhger@gmail.com>"]
repository = "https://github.com/kpeez/deep-neuronmorpho"
documentation = "https://kpeez.github.io/deep-neuronmorpho/"
readme = "README.md"
packages = [{ include = "deep_neuronmorpho" }]

[tool.poetry.dependencies]
python = "^3.11, <3.12"
pandas = "2.*"
numpy = "^1.24"
matplotlib = "^3.6"
seaborn = "^0.12"
scikit-learn = "^1.4"
torch = "^2.0.0"
dgl = "1.1.3"
xgboost = "^2.0"
umap-learn = "^0.5.4"
pyyaml = "^6.0"
pyarrow = "^15.0"
morphopy = "^0.7.2"
tensorboard = "^2.12.2"
typer = "^0.9"
pydantic = "^2.3.0"

[tool.poetry.group.dev.dependencies]
ruff = "*"
mypy = "^1.8.0"
pre-commit = "^3"
ipykernel = "^6"
notebook = "^7"
pandas-stubs = "*"

[tool.poetry.group.test.dependencies]
pytest = "^8"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-material = "^8.5.10"
mkdocstrings = { extras = ["python"], version = "^0.19.0" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [".venv", "external"]

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  "W",
  # pyflakes
  "F",
  # pylint
  "PL",
  # isort
  "I",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # flake8-comprehensions
  "C4",
  # ruff
  "RUF",
]
fixable = ["ALL"]
ignore = [
  # too many arguments
  "PLR0913",
  # magic number
  "PLR2004",
  # line too long
  "E501",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "D104"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
files = ["deep_neuronmorpho"]
plugins = "numpy.typing.mypy_plugin"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
exclude = [".venv", "tests", "external"]

[[tool.mypy.overrides]]
module = [
  "deep_neuronmorpho.*",
  "deep_neuronmorpho.*.*",
  "morphopy.*",
  "networkx",
  "scipy.*",
  "sklearn.*",
  "dgl.*",
]
ignore_missing_imports = true
warn_return_any = false
disallow_any_unimported = false
disable_error_code = "attr-defined"
