_target_: pytorch_lightning.Trainer
max_steps: ${training.max_steps}
logger: ${training.logger}
callbacks: ${training.callbacks}
accelerator: auto
devices: auto
deterministic: true
num_sanity_val_steps: 0
val_check_interval: ${training.eval_interval}
log_every_n_steps: ${training.logging_steps}
