_target_: pytorch_lightning.Trainer
max_steps: ${training.max_steps}
logger: ${training.logger}
callbacks: ${training.callbacks}
accelerator: auto
devices: auto
deterministic: true
log_every_n_steps: ${training.logging_steps}
