defaults:
  - _self_
  - model: macgnn
  - data: default
  - training/trainer: default
  - training/lightning_module: contrastive
  - training/loss: ntxent
  - training/optimizer: adam
  - training/scheduler: steplr
  - training/logger: tensorboard
  - training/callbacks: checkpoint

hydra:
  run:
    dir: ${run_dir}/${hydra:runtime.choices.model}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: false

run_dir: ./runs/demo_runs/${now:%Y-%m-%d_%H-%M-%S}
seed: 42
ckpt_path: null

augmentations:
  jitter: 1.0
  translate: 10.0
  rotation_axis: y
  num_drop_branches: 10
