defaults:
  - _self_
  - model: macgnn
  - data: default
  - trainer: default
  - lightning_module: contrastive
  - loss: ntxent
  - optimizer: adam
  - scheduler: steplr
  - logger: tensorboard
  - callbacks: checkpoint

hydra:
  run:
    dir: ${run_dir}/${hydra:runtime.choices.model}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: false

run_dir: ./runs/demo_runs/${now:%Y-%m-%d_%H-%M-%S}
seed: 42
ckpt_path: null
