defaults:
  - _self_
  - model: macgnn
  - training/optimizer: adam
  - training/scheduler: steplr
  - training/logger: tensorboard
  - training/callbacks: checkpoint
  - training/trainer: default

hydra:
  run:
    dir: ${training.logging_dir}/${hydra:runtime.choices.model}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: false

data:
  train_dataset: ./datasets/processed/m1_patchseq/data
  eval_dataset: null
  num_nodes: 200
  feat_dim: 3

training:
  logging_dir: ./runs/demo_runs/
  max_steps: 10
  batch_size: 64
  eval_interval: 1
  random_state: 42
  logging_steps: 1
  num_workers: 0

augmentations:
  jitter: 1.0
  translate: 10
  rotation_axis: y
  num_drop_branches: 10
