_target_: deep_neuronmorpho.models.graphdino.GraphDINO
transformer:
  _target_: deep_neuronmorpho.models.graphdino.GraphTransformer
  n_nodes: ${data.num_nodes}
  dim: 32
  depth: 7
  num_heads: 8
  feat_dim: ${data.feat_dim}
  pos_dim: 32
  num_classes: 1000
num_classes: 1000
moving_average_decay: 0.999
center_moving_average_decay: 0.9
teacher_temp: 0.06
