# model config
dirs:
  data: "../datasets/demo_gnn_data/processed/dgl_datasets"
  results: "../datasets/demo_gnn_data/expt_results/supervised"

datasets:
  eval_train: "demo-neuromorpho_benchmark_radius-train"
  eval_test: "demo-neuromorpho_benchmark_radius-test"

model:
  name: "macgnn_super_demo"
  num_gnn_layers: 5
  num_mlp_layers: 2
  hidden_dim: 64
  output_dim: 7
  dropout_prob: 0.5
  attrs_streams:
    geometric: [0, 3] # x, y, z
    topological: [4, 17] # euc_dist, path_dist, angles/branches
  use_edge_weight: True # attention
  learn_eps: False # learnable eps in GINConv
  neighbor_aggregation: "sum" # "sum", "mean", "max"
  graph_pooling_type: "max" # "sum", "mean", "max"
  gnn_layer_aggregation: "sum" # ["sum", "mean", "max", "wsum", "cat"]
  stream_aggregation: "wsum" # ["sum", "mean", "max", "wsum", "cat"]

# Training configuration
training:
  batch_size: 128
  eval_interval: 1
  epochs: 5
  patience: 60
  lr_init: 0.01
  random_seed: 42 # optional
  optimizer: "adam"
  lr_scheduler: "step" # ["cosine", "step"]
  lr_decay_steps: 20
  lr_decay_rate: 0.6
