datasets:
  root: "../data/demo_gnn_data/processed/dgl_datasets"
  contra_train: "mouse_resampled_10um-train"
  cls_train: "neuromorpho_benchmark_train"
  cls_test: "neuromorpho_benchmark_test"

model:
  name: "macgnn"
  num_gnn_layers: 5
  num_mlp_layers: 2
  hidden_dim: 64
  output_dim: 320 # hidden_dim * num_gnn_layers
  dropout_prob: 0.5
  attrs_streams:
    geometric: [0, 2] # x, y, z
    topological: [3, 16] # euc_dist, path_dist, angles/branches
  use_edge_weight: True # attention
  learn_eps: False # learnable eps in GINConv
  graph_pooling_type: "max" # "sum", "mean", "max"
  neighbor_aggregation: "sum" # "sum", "mean", "max"
  gnn_layers_aggregation: "cat" # ["sum", "mean", "max", "wsum", "cat"]
  stream_aggregation: "wsum" # ["sum", "mean", "max", "wsum", "cat"]

# Training configuration
training:
  batch_size: 64
  contra_loss_temp: 0.2
  max_epochs: 400
  patience: 60
  lr_init: 0.01
  optimizer: "adam"
  lr_scheduler: "step" # ["cosine", "step"]
  lr_decay_steps: 20
  lr_decay_rate: 0.6

# Augmentation info
augmentation:
  order: [perturb, rotate, drop_branches]
  params:
    perturb:
      prop: 0.5
      std_noise: 2.0
    rotate: {} # no args needed
    drop_branches:
      prop: 0.02
      deg_power: 1.0

# Output configuration
output:
  log_dir: "../data/demo_gnn_data/outputs/logs"
  chkpt_dir: "../data/demo_gnn_data/outputs/models"
