# model config
dirs:
  data: "../datasets/allen_cell_types/processed/"
  logging: "../runs/demo_run/"

datasets:
  contra_train: "allen_cell_types-dimfeats17-self_loop"
  eval_train: "allen_cell_types-dimfeats17-self_loop"
  eval_test: "allen_cell_types-dimfeats17-self_loop"

model:
  name: "macgnnv2_demo"
  num_gnn_layers: 5
  num_mlp_layers: 2
  hidden_dim: 64
  output_dim: 64
  dropout_prob: 0.5
  attrs_streams:
    geometric: [0, 3] # x, y, z, radius
    topological: [4, 16] # euc_dist, path_dist, angles/branches
  use_edge_weight: True # attention
  learn_eps: False # learnable eps in GINConv
  neighbor_aggregation: "sum" # "sum", "mean", "max"
  graph_pooling_type: "max" # "sum", "mean", "max"
  gnn_layer_aggregation: "cat" # ["sum", "mean", "max", "wsum", "cat"]
  stream_aggregation: "wsum" # ["sum", "mean", "max", "wsum", "cat"]

# Training configuration
training:
  batch_size: 64
  contra_loss_temp: 0.2
  eval_interval: 1
  save_every: 1
  epochs: 1
  patience: 60
  optimizer: "adam"
  lr: 0.01
  lr_scheduler: # ["cosine", "step"]
    kind: "step"
    step_size: 20
    factor: 0.6
  random_state: 42 # optional
  logging_steps: 1

# Augmentation info
augmentation:
  order: [perturb, rotate, drop_branches]
  params:
    perturb:
      prop: 0.5
      std_noise: 2.0
    rotate: {} # no args needed
    drop_branches:
      prop: 0.02
      deg_power: 1.0
      path_dist_idx: 4
