# Data configuration
root_path: "insert_path"
data:
  train_data_path: "data/train/"
  val_data_path: "data/validation/"
  test_data_path: "data/test/"
  num_workers: 1
  batch_size: 64
  normalize_features: True

# Model configuration
model:
  num_gnn_layers: 5
  num_mlp_layers: 2
  hidden_dim: 64
  output_dim: 320 # hidden_dim * num_gnn_layers
  dropout_prob: 0.5
  attrs_streams:
    geometric: (0, 3)
    topological: (4, 17)
  # norm_attrs: False
  #use_self_loop: True # net_learn_eps = False in Zhao code
  use_edge_weight: False # attention
  learn_eps: False # learnable eps in GINConv
  graph_pooling_type: "max" # "sum", "mean", "max"
  neighbor_aggregation: "sum" # "sum", "mean", "max"
  gnn_layers_aggregation: "cat" # ["sum", "mean", "max", "wsum", "cat"]
  stream_aggregation: "wsum" # ["sum", "mean", "max", "wsum", "cat"]

# Trainig configuration
training:
  lr_init: 0.01
  seed_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  contra_loss_temp: 0.2
  shuffle: True
  max_epochs: 400
  lr_patience_epochs: 60
  lr_scheduler: "step" # ["cosine", "step"]
  decay_steps: 20
  decay_rate: 0.6

# Augmentation info
augmentation:
  order: [perturb, rotate]
  params:
    perturb:
      prop: 0.5
      std_noise: 2.0
    rotate: {} # no args needed
    # drop_branches:
    #   prop: 0.02
    #   deg_power: 2.0

# Logging configuration
logging:
  log_dir: "saved/logs"
  chkpt_dir: "saved/models"
